server: 
  port: ${PROD_PORT:20002} 
spring:
  application:
    name: config-client
  profiles: 
    active: stream-producer-dev-app
  config:
    import: optional:configserver:http://localhost:8888
    name: stream-producer-dev-app
  
    
logging:
  level:
    ROOT: INFO
    org.spring.framework: DEBUG