server:
  port: 8888
  
spring: 
   application: 
     name: configserver
   cloud: 
     config: 
       server:
         git: 
           uri: https://github.com/pandeych009/itlogiclab-spring-cloud-config-server-repository
           username: pandeych009
           password: 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
           default-label: dev
           clone-on-start: true
           basedir: target/config
     fail-fast: true     

logging:
  level:
    ROOT: INFO
    org.spring.framework.cloud.config: DEBUG 